# Generated by Django 4.1.2 on 2022-10-12 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="grade",
            new_name="grade_id",
        ),
    ]
